server: ## Config Web Server
   port: 22000
   servlet.contextPath: /rtdbmaintainer
  
master: 
   datasource:
      hikari: 
        jdbc-url: jdbc:mysql://localhost:3306/onesaitplatform_master_config?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true
        username: root
        password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
        driver-class-name: com.mysql.cj.jdbc.Driver
        pool-name: master-hikari-pool
        minimum-idle: 1
        maximum-pool-size: 3
        connection-timeout: 10000
onesaitplatform:
   audit.global.notify: true
   binary-repository:
      type: mongo
   rtdb-to-hdb:
      path: /usr/local/files/
   rtdb-opsclean-delay: 600000
   rtdb-opsclean-kill: 10
   router.avoidsslverification: true
   router.alternativeURL: http://localhost:20000/router/router/
   locale.default: en
   encription.key: sofia2
   database.elasticsearch.enabled: false
   database.mongodb:
      database: onesaitplatform_rtdb
      authenticationDatabase:  #admin
      servers: localhost:27017
      autoConnectRetry: true
      socketTimeout: 5000
      maxAutoConnectRetryTime: 5000
      maxWaitTime: 5000
      useAuth: false
      username: #username
      password: #password
      readFromSecondaries: false
      queries.executionTimeout: 5000
      queries.defaultLimit: 2000
      queries.maxConcurrentQueries: 3
      writeConcern: UNACKNOWLEDGED
      tools.useSequentialOps: true   
      tools.mongoexport.path: mongoexport
      tools.mongoimport.path: mongoimport
      tools.mongoshell.path: mongo    
      digitaltwin.database: digital_twin
      export.path: /tmp/export/
      mongoexport.path: s:/tools/mongo/bin/mongoexport
   graylog:
      enabled: false
      host: 127.0.0.1
      port: 12201
   
   
management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always
 
spring: ## General Config  
   application.name: onesaitplatform-rtdb-maintainer
   datasource:
     hikari:
      jdbc-url: jdbc:mysql://localhost:3306/onesaitplatform_config?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true&nullDatabaseMeansCurrent=true
      username: root
      password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
      connection-timeout: 10000
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 5
      
           
   jpa:
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      # Hibernate ddl auto (create, create-drop, validate, update)
      hibernate.ddl-auto: validate
      hibernate.temp.use_jdbc_metadata_defaults: false
   boot.admin: #Spring Boot Admin Config   
      client.url: http://localhost:18100/monitoring
      client.username: operations
      client.password: changeIt2019!
      client.metadata.user.name: ${spring.boot.admin.username}
      client.metadata.user.password: ${spring.boot.admin.password}

quartz:      
   datasource:
     hikari: 
        jdbc-url: "@onesaitplatform.quartzURL@"
        username: root
        password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
        driver-class-name: com.mysql.cj.jdbc.Driver
        connection-timeout: 10000
        minimum-idle: 3
        maximum-pool-size: 6 
          
   jpa:
      ## Hibernate Properties
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      # Hibernate ddl auto (create, create-drop, validate, update)
      properties.hibernate.hbm2ddl.auto: validate
   autoStartupSchedulers:
      - batchScheduler
      - okpiScheduler
      - expirationUsersScheduler
      - expirationResetUsersScheduler

## LOGGING CONF
logging:
   path: ./target/ 
   file: ${spring.application.name}
   level:
      com.minsait: INFO 
