server: ## Config Web Server
   port: 22000
   contextPath: /rtdbmaintainer
  
master: 
   datasource:
      url: jdbc:mysql://localhost:3306/onesaitplatform_master_config?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true
      username: root
      password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
      driver-class-name: com.mysql.jdbc.Driver
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1      
      validationQueryTimeout: 5
      # Number of ms to wait before throwing an exception if no connection is available.
      max-wait: 10000
      # Maximum number of active connections that can be allocated from this pool at the same time.
      max-active: 2
      initial-size: 1
      max-idle: 2
      min-idle: 1
      removeAbandoned: true
onesaitplatform:
   audit.global.notify: true
   binary-repository:
      type: mongo
   rtdb-to-hdb:
      path: /usr/local/files/
   rtdb-opsclean-delay: 600000
   rtdb-opsclean-kill: 10
   router.avoidsslverification: true
   router.alternativeURL: http://localhost:20000/router/router/
   locale.default: en
   encription.key: sofia2
   database.elasticsearch.enabled: false
   database.mongodb:
      database: onesaitplatform_rtdb
      authenticationDatabase:  #admin
      servers: localhost:27017
      autoConnectRetry: true
      socketTimeout: 5000
      maxAutoConnectRetryTime: 5000
      maxWaitTime: 5000
      useAuth: false
      username: #username
      password: #password
      readFromSecondaries: false
      queries.executionTimeout: 5000
      queries.defaultLimit: 2000
      queries.maxConcurrentQueries: 3
      writeConcern: UNACKNOWLEDGED
      tools.useSequentialOps: true   
      tools.mongoexport.path: mongoexport
      tools.mongoimport.path: mongoimport
      tools.mongoshell.path: mongo    
      digitaltwin.database: digital_twin
      export.path: /tmp/export/
      mongoexport.path: s:/tools/mongo/bin/mongoexport
   
 
spring: ## General Config  
   application.name: onesaitplatform-rtdb-maintainer
   datasource: ## JPA Config
      url: jdbc:mysql://localhost:3306/onesaitplatform_config?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true&nullDatabaseMeansCurrent=true
      username: root
      password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
      driver-class-name: com.mysql.jdbc.Driver
      test-on-borrow: true
      validation-query: SELECT 1
      validationQueryTimeout: 5
      test-while-idle: true
      # Number of ms to wait before throwing an exception if no connection is available.
      max-wait: 10000
      # Maximum number of active connections that can be allocated from this pool at the same time.
      max-active: 30
      initial-size: 10
      max-idle: 30
      min-idle: 10
      
            
   jpa:
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      # Hibernate ddl auto (create, create-drop, validate, update)
      hibernate.ddl-auto: validate
      hibernate.temp.use_jdbc_metadata_defaults: false
  

quartz:      
   datasource:
      url: jdbc:mysql://localhost:3306/onesaitplatform_scheduler?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
      driver-class-name: com.mysql.jdbc.Driver
      test-on-borrow: true
      validation-query: SELECT 1
      validationQueryTimeout: 5
      test-while-idle: true  
      # Number of ms to wait before throwing an exception if no connection is available.
      max-wait: 10000
      # Maximum number of active connections that can be allocated from this pool at the same time.
      max-active: 10
      initial-size: 3
      max-idle: 10
      min-idle: 3  
          
   jpa:
      ## Hibernate Properties
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      # Hibernate ddl auto (create, create-drop, validate, update)
      properties.hibernate.hbm2ddl.auto: update
   autoStartupSchedulers:
      - batchScheduler
      - okpiScheduler
      - expirationUsersScheduler

## LOGGING CONF
logging:
   path: ./target/ 
   file: ${spring.application.name}
   level:
      com.minsait: INFO 
