master:
   datasource:
     hikari:
      jdbc-url: ${CONFIGDBMASTERURL}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}
      maximum-pool-size: ${CONFIGDB_MAX_ACTIVE}
      driver-class-name: ${CONFIGDB_DRIVER}

onesaitplatform:
   database.mongodb:
      database: ${REALTIMEDBNAME}
      servers: ${REALTIMEDBSERVERS}
      authenticationDatabase: ${REALTIMEDBAUTHDB}
      useAuth: ${REALTIMEDBUSEAUTH}
      username: ${REALTIMEDBUSER}
      password: ${REALTIMEDBPASS}
      writeConcern: ${REALTIMEDBWRITECONCERN} 
      quasar.connector.http.endpoint: http://${QUASARHOST}:${QUASARPORT}/query/fs/
   database.elasticsearch.enabled: ${ELASTICSEARCH_ENABLED}
   router.alternativeURL: http://routerservice:20000/router/router/
   audit.global.notify: ${AUDITGLOBALNOTIFY}
   hazelcast.service.discovery.strategy: ${HZ_SERVICE_DISCOVERY_STRATEGY}
   hazelcast.service.discovery.zookeeper.url: ${HZ_ZOOKEEPER_URL}
   graylog:
      enabled: ${GRAYLOG_ENABLED}
      host: ${GRAYLOG_HOST}
      port: ${GRAYLOG_PORT}
   database.configdb.export:
      minio.enabled: ${MINIO_ENABLED}
      tmp.path: /temp/minio/backup/
spring:
   datasource:
     hikari:
      jdbc-url: ${CONFIGDBURL}${DBADDPROPS}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}
      connection-timeout: ${DS_MAX_WAIT_MILLIS}
      maximum-pool-size: ${DS_MAX_ACTIVE}
      minimum-idle: ${DS_MIN_IDLE}
      driver-class-name: ${CONFIGDB_DRIVER}
   boot.admin: #Spring Boot Admin Config
      client.url: http://monitoringuiservice:18100/monitoring
      client.instance.service-url: http://rtdbmaintainerservice:${server.port}${server.servlet.contextPath}/
      client.username: ${SBA_USERNAME}
      client.password: ${SBA_SECRET}
   data.mongodb:
      host: ${REALTIMEDBSERVERS}
   elasticsearch.jest:
      uris: http://${ELASTICDBHOST}:${ELASTICDBPORT}
   jpa:
      properties.hibernate.dialect: ${CONFIGDB_DIALECT}
quartz:
    datasource:
     hikari:
        jdbc-url: ${SCHEDULERDBBURL}${DBADDPROPS}
        username: ${SCHEDULERDBBUSER}
        password: ${SCHEDULERDBBPASS}
        driver-class-name: ${SCHEDULERDBBDRIVER}
    jpa:
      properties.hibernate.dialect: ${SCHEDULERDBBDIALECT}
    driverDelegateClass: ${QUARTZ_DRIVER}
## LOGGING CONF
logging:
   file.path: /var/log/platform-logs
