version: '2'
services:
  registryui:
    scale: 1
    start_on_create: true
  oauthservice:
    scale: 1
    start_on_create: true
  kafkamonitoringservice:
    scale: 1
    start_on_create: true
  streamsets:
    scale: 1
    start_on_create: true
  schedulerdb:
    scale: 1
    start_on_create: true
  configinit:
    scale: 1
    start_on_create: true
  datahistorian:
    scale: 1
    start_on_create: true
  apimanagerservice:
    scale: 1
    start_on_create: true
  digitaltwinbrokerservice:
    scale: 1
    start_on_create: true
  cacheservice:
    scale: 1
    start_on_create: true
  flowengineservice:
    scale: 1
    start_on_create: true
  controlpanelservice:
    scale: 1
    start_on_create: true
  elasticdb:
    scale: 1
    start_on_create: true
  zookeeper:
    scale: 1
    start_on_create: true
  clm:
    scale: 1
    start_on_create: true
  ideaasservice:
    scale: 1
    start_on_create: true
  devicesimulator:
    scale: 1
    start_on_create: true
  videobrokerservice:
    scale: 1
    start_on_create: true
  smartcities-administrator:
    scale: 1
    start_on_create: true
  zeppelin:
    scale: 1
    start_on_create: true
  configdb:
    scale: 1
    start_on_create: true
  rtdbmaintainerservice:
    scale: 1
    start_on_create: true
  mlm:
    scale: 1
    start_on_create: true
  iotbrokerservice:
    scale: 1
    start_on_create: true
  govconsole:
    scale: 1
    start_on_create: true
  loadbalancerservice:
    scale: 1
    start_on_create: true
  quasar:
    scale: 2
    start_on_create: true
  kafka:
    scale: 1
    start_on_create: true
  monitoringuiservice:
    scale: 1
    start_on_create: true
  haproxy:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: tcp
        service: iotbrokerservice
        source_port: 1883
        target_port: 1883
      - priority: 2
        protocol: tcp
        service: iotbrokerservice
        source_port: 8883
        target_port: 8883
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  dashboardengineservice:
    scale: 1
    start_on_create: true
  routerservice:
    scale: 1
    start_on_create: true
  clm-environment:
    scale: 1
    start_on_create: true
  realtimedb:
    scale: 1
    start_on_create: true
