server: ## Config Web Server
   port: 20200
   contextPath: /rules-engine
   jetty.max-http-post-size: 20000000      
   
master: 
   datasource:
      url: jdbc:mysql://localhost:3306/onesaitplatform_master_config?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true
      username: root
      password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
      driver-class-name: com.mysql.jdbc.Driver
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1      
      validationQueryTimeout: 5
      # Number of ms to wait before throwing an exception if no connection is available.
      max-wait: 10000
      # Maximum number of active connections that can be allocated from this pool at the same time.
      max-active: 2
      initial-size: 1
      max-idle: 2
      min-idle: 1
      removeAbandoned: true

spring: ## General Config  
   application.name: onesaitplatform-rules-engine
   datasource: ## JPA Config
      url: jdbc:mysql://localhost:3306/onesaitplatform_config?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true&nullDatabaseMeansCurrent=true
      username: root
      password: changeIt!
      driver-class-name: com.mysql.jdbc.Driver
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1      
      validationQueryTimeout: 5
      # Number of ms to wait before throwing an exception if no connection is available.
      max-wait: 10000
      # Maximum number of active connections that can be allocated from this pool at the same time.
      max-active: 30
      initial-size: 10
      max-idle: 30
      min-idle: 10
      removeAbandoned: true
     
   jpa:
      open-in-view: false
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      # Hibernate ddl auto (create, create-drop, validate, update
      hibernate.ddl-auto: validate
      properties:
        hibernate:
          format_sql: false
          show_sql: false

onesaitplatform:
  rules-engine:
    threading.core-pool-size: 5
    threading.max-pool-size: 10
    threading.queue-capacity: 50
    hazelcast:
       topic_domains: topicDomains
       topic_rules: topicRules
       topicAsyncComm: topicAsyncComm

# all access to actuator endpoints without security
management.security.enabled: false

security:
  oauth2:
    client:
      clientId: onesaitplatform
      clientSecret: onesaitplatform
      accessTokenUri: http://localhost:21000/oauth-server/oauth/token
      userAuthorizationUri: http://localhost:21000/oauth-server/oauth/authorize
      checkTokenEndpointUrl: http://localhost:21000/oauth-server/oauth/check_token
      useCurrentUri: true
    resource:
      userInfoUri: http://localhost:21000/oauth-server/user

## LOGGING CONF
logging:
   config: classpath:logback-spring.xml
   path: ./target/ 
   file: ${spring.application.name}
   level:
      com.minsait: DEBUG 
      org.springframework.web: ERROR
