spring: ## General Config  
   datasource: ## JPA Config
      url: ${CONFIGDBURL}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS} 
      time-between-eviction-runs-millis: ${DS_TIME_BETWEEN_EVICTION_RUNS_MILLIS}
      min-evictable-idle-time-millis: ${DS_MIN_EVICTABLE_IDLE_TIME_MILLIS}
      max-wait-millis: ${DS_MAX_WAIT_MILLIS}
      max-wait: ${DS_MAX_WAIT}
      initial-size: ${DS_INITIAL_SIZE}
      max-active: ${DS_MAX_ACTIVE}
      max-idle: ${DS_MAX_IDLE}
      min-idle: ${DS_MIN_IDLE}
      removeAbandoned: ${DS_REMOVE_ABANDONED}
      removeAbandonedTimeout: ${DS_REMOVE_ABANDONED_TIMEOUT}
onesaitplatform:
   hazelcast.service.discovery.strategy: ${HZ_SERVICE_DISCOVERY_STRATEGY}
   hazelcast.service.discovery.zookeeper.url: ${HZ_ZOOKEEPER_URL}
security:
  oauth2:
    client:
      clientId: onesaitplatform
      clientSecret: onesaitplatform
      accessTokenUri: https://${SERVER_NAME}/oauth-server/oauth/token
      userAuthorizationUri: https://${SERVER_NAME}/oauth-server/oauth/authorize
      checkTokenEndpointUrl: https://${SERVER_NAME}/oauth-server/oauth/check_token
      useCurrentUri: true
    resource:
      userInfoUri: https://${SERVER_NAME}/oauth-server/user

## LOGGING CONF
logging:
   path: /var/log/platform-logs
