version: "2.1"

services:  
  zookeeper:
    #image: local/zookeeper:6.1.1
    image: registry.onesaitplatform.com/onesaitplatform/zookeeper-secured:cp-6.1.1
    container_name: zookeeper  
    ports:
     - "2181:2181"
   # volumes:
   #  - /data/docker_images/zookeeper/data:/var/lib/zookeeper/data
    # - /data/docker_images/zookeeper/log:/var/lib/zookeeper/log
   #  - /data/docker_images/zookeeper/tmp:/tmp/zookeeper
    environment:
       ZOOKEEPER_CLIENT_PORT: "2181"
       #ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: "DEBUG"
       ZOOKEEPER_DATADIR: "/tmp/zookeeper"
       ZOOKEEPER_SECURITY_PROVIDER_1: "authentication.server.PlainSaslServerProvider"
       ZOOKEEPER_AUTHPROVIDER_1: "authentication.server.PlainSaslServerProvider"
       ZOOKEEPER_SECURITY_AUTHPROVIDER_1: "authentication.server.PlainSaslServerProvider"
       ZOOKEEPER_REQUIRECLIENTAUTHSCHEME: "sasl"
       ZOOKEEPER_JAASLOGINRENEW: "3600000"
       KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/zookeeper_jaas.conf -Dzookeeper.authProvider.1=authentication.server.PlainSaslServerProvider"
       ZOOKEEPER_SNAPSHOT_TRUST_EMPTY: "true"
     
  kafka:
    #image: local/kafka:6.1.1
    image: registry.onesaitplatform.com/onesaitplatform/kafka-secured:cp-6.1.1
    container_name: kafka    
    ports:
     - "9095:9095"
     - "9092:9092" 
    #volumes:
     # - /data/docker_images/kafka/data:/var/lib/kafka/data
     # - /data/docker_images/kafka/tmp:/tmp/kafka
      #- /data/docker_images/kafka/logs:/tmp/kafka-logs
      #- /data/docker_images/kafka/logs-plat:/var/log/platform-logs
    environment:
       ZOOKEEPER_SERVER: "10.101.219.50"
       SERVER_NAME: "10.101.219.50"
       KAFKA_BROKER_ID: "1"
       KAFKA_ZOOKEEPER_CONNECT: "10.101.219.50:2181"
       KAFKA_LISTENERS: "SASL_PLAINTEXT://:9095, PLAINTEXT://:9092"
       KAFKA_ADVERTISED_LISTENERS: "SASL_PLAINTEXT://10.101.219.50:9095,PLAINTEXT://10.101.219.50:9092"
       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
       KAFKA_INTER_BROKER_LISTENER_NAME: "SASL_PLAINTEXT"
       KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
       KAFKA_SASL_ENABLED_MECHANISMS: "PLAIN"
       KAFKA_AUTHORIZER_CLASS_NAME: "kafka.security.auth.SimpleAclAuthorizer"
       #KAFKA_AUTHORIZER_CLASS_NAME: "authentication.OnesaitPlatformAclAuthorizer"
       KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
       KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
       KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
       KAFKA_SECURITY_PROVIDER_1: "authentication.server.PlainSaslServerProvider"
       KAFKA_SOCKET_SEND_BUFFER_BYTES: "102400"
       KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: "102400"
       KAFKA_SOCKET_REQUEST_MAX_BYTES: "104857600"
       #KAFKA_LOG4J_ROOT_LOGLEVEL: "DEBUG"
       CUB_CLASSPATH: "/usr/share/java/cp-base/*:/usr/share/java/cp-base-new/*:/usr/share/java/kafka/*"
       ZOOKEEPER_SASL_ENABLED: "true"
       KAFKA_SUPER_USERS: "User:admin"
       KAFKA_DEFAULT_REPLICATION_FACTOR: 1
       KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
       KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    depends_on:
     - "zookeeper"      
   
