kind: Deployment
apiVersion: apps/v1
metadata:
  name: ftp-server
  generation: 6
  namespace: operaciones-digitales
  labels:
    app: ftp-server
    app.kubernetes.io/managed-by: Helm
    group: onesait-platform
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ftp-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ftp-server
    spec:
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 1536Mi
            requests:
              cpu: 1m
              memory: 1Mi
          readinessProbe:
            tcpSocket:
              port: 22
            initialDelaySeconds: 20
            timeoutSeconds: 2
            periodSeconds: 5
            successThreshold: 2
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: ftp-server
          ports:
            - name: 22tcp22
              containerPort: 22
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: 'atmoz/sftp:latest'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      serviceAccount: lanza-sa
      serviceAccountName: lanza-sa
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
