version: "2.1"

services:
  quasar:
    image: registry.onesaitplatform.com/onesaitplatform/quasar:latest
    container_name: quasar
    ports:
      - "10800:10800"
    environment:
      - REALTIMEDBUSEAUTH=false
      - AUTHPARAMS= 
      - REALTIMEDBSERVERS=192.168.1.3:27017
      - AUTHDB=   
      - CONSUL_DATA_DIR=/consul/data
    extra_hosts:
      - "realtimedb:192.168.1.3"
    dns:
      - "10.5.0.2:8600"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
  consul-agent:
    image: consul:latest
    container_name: consul-agent
    ports:
      - "8500:8500"
      - "8600:8600"
    volumes:
      - "./config.hcl:/etc/consul/config.hcl"
      - "/tmp/consul:/consul/data"
    privileged: true
    command: agent -dev -ui -datacenter lab -client 0.0.0.0 -config-file /etc/consul/config.hcl -data-dir /consul/data
    dns:
      - "10.5.0.2:8600"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
  sidecar-controlpanel:
    image: consul-proxy:latest
    container_name: controlpanel-proxy
    ports:
      - "11800:11800"
    command: -sidecar-for controlpanel -http-addr=10.5.0.2:8500 
    depends_on:
      - "consul-agent"
    dns:
      - "10.5.0.2:8600"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
  sidecar-quasar:
    image: consul-proxy:latest
    container_name: quasar-proxy
    command: -sidecar-for quasar -http-addr=10.5.0.2:8500 -log-level=DEBUG
    depends_on:
      - "consul-agent"
    dns:
      - "10.5.0.2:8600"
    extra_hosts:
      - "quasar:10.5.0.4"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6



networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/16



#TO-DO meter en el sidecar los mismos