version: "2.1"

services:
  quasar:
    image: registry.onesaitplatform.com/onesaitplatform/quasar:latest
    container_name: quasar
    ports:
      - "10800:10800"
    environment:
      - REALTIMEDBUSEAUTH=false
      - AUTHPARAMS= 
      - REALTIMEDBSERVERS=192.168.1.4:27017
      - AUTHDB=   
      - CONSUL_DATA_DIR=/consul/data
    extra_hosts:
      - "realtimedb:192.168.1.4"
    dns:
      - "10.5.0.2:8600"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
  sidecar-quasar:
    image: consul-proxy:latest
    container_name: quasar-proxy
    environment:
      - CONSUL_AGENT=192.168.1.4
      - SERVICE_NAME=quasar 
      - REALTIMEDBSERVERS=192.168.1.4:27017
      - PORT=10800
      - STACK=NA
    extra_hosts:
      - "quasar:10.5.0.4"
      - "localhost:192.168.1.4"
      - "NA-quasar-quasar-sidecar-1:10.5.0.6"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/16