onesaitplatform:
   hazelcast.service.discovery.strategy: ${HZ_SERVICE_DISCOVERY_STRATEGY}
   hazelcast.service.discovery.zookeeper.url: ${HZ_ZOOKEEPER_URL}

spring:
   boot.admin: #Spring Boot Admin Config    
      client.url: http://monitoringuiservice:18100/monitoring    
      client.instance.service-url: http://cacheservice:${server.port}${server.servlet.contextPath}/ 

logging:
   path: /var/log/platform-logs