server:
   max-http-header-size: 10000000
   port: 18080
   jetty.max-http-form-post-size: 20000000
   tomcat.max-http-form-post-size: 20000000
   forward-headers-strategy: native
   servlet:
      contextPath: /plugins-manager



spring:
   servlet.multipart.max-file-size: 100MB
   servlet.multipart.max-request-size: 100MB
   autoconfigure:
      exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
   application.name: plugin-manager
   datasource:
      url: jdbc:mysql://localhost:3306/onesaitplatform_master_config?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true&nullDatabaseMeansCurrent=true
      username: root
      password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph)
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: 10000
#      jdbc-url: jdbc:postgresql://localhost:5432/onesaitplatform_config
#      username: postgres
#      password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph)
#      driver-class-name: org.postgresql.Driver
      minimum-idle: 2
      maximum-pool-size: 30


   jpa:
      open-in-view: false
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#      properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
      # Hibernate ddl auto (create, create-drop, validate, update
      hibernate.ddl-auto: update
      properties:
        hibernate:
          format_sql: false
          show_sql: false
   
   
onesaitplatform:
   plugins.path: /tmp/plugins
