spring:
   datasource:
      url:  ${CONFIGDBMASTERURL}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}
      driver-class-name: ${CONFIGDB_DRIVER}
   jpa:
      properties.hibernate.dialect: ${CONFIGDB_DIALECT}
   
   
onesaitplatform:
   plugins.path: /plugins
