server: ## Config Web Server
   port: 8085
   servlet.contextPath: /bpm-engine
   max-http-header-size: 20000
   tomcat:
      access_log_enabled: true
      basedir: target/tomcat
   jetty.max-http-form-post-size: 20000000
onesaitplatform:
    authentication:
      oauth:
        osp-keycloak: false
    camunda:
       admin-user: administrator
       import-users: true
    graylog:
       enabled: false
       host: 127.0.0.1
       port: 12201
      
master: 
   datasource:
      hikari: 
        jdbc-url: jdbc:mysql://localhost:3306/onesaitplatform_master_config?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true
        username: root
        password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
        driver-class-name: com.mysql.cj.jdbc.Driver
        pool-name: master-hikari-pool
        minimum-idle: 1
        maximum-pool-size: 2
        connection-timeout: 10000
        
management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always

spring: ## General Config  
   main:
      allow-circular-references: true
      allow-bean-definition-overriding: true
   boot.admin: #Spring Boot Admin Config   
      client.url: http://localhost:18100/monitoring
      client.username: operations
      client.password: changeIt2019!
      client.instance.metadata.user.name: ${spring.boot.admin.client.username}
      client.instance.metadata.user.password: ${spring.boot.admin.client.password}
   main.allow-bean-definition-overriding: true
   application.name: onesaitplatform-bpm-engine
   datasource:
     hikari:
      jdbc-url: jdbc:mysql://localhost:3306/onesaitplatform_config?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true&nullDatabaseMeansCurrent=true
      username: root
      password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
      connection-timeout: 10000
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 10
     
   jpa:
      open-in-view: false
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.ddl-auto: validate

      properties:
        hibernate:
          format_sql: false
          show_sql: false
   security:
      oauth2:
        client:
          registration:
            onesaitplatform-code:
              provider: im-base
              client-id: onesaitplatform
              client-secret: onesaitplatform 
              authorization-grant-type: authorization_code
              redirect-uri: "{baseUrl}/login/oauth"
              scope: opeind
          provider:
            im-base:
              authorization-uri: http://localhost:18000/controlpanel/oauth/authorize
              token-uri: http://localhost:18000/controlpanel/oauth/token
              user-info-uri: http://localhost:18000/controlpanel/user
              
camunda.datasource:
      jdbc-url: jdbc:mysql://localhost:3306/onesaitplatform_bpm?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true&nullDatabaseMeansCurrent=true
      username: root
      password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
      connection-timeout: 10000
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 10
camunda.bpm:
    authorization.enabled: true
    filter.create: All


security:
  oauth2:
    client:
      logoutUrl: http://localhost:18000/controlpanel/logout
      useCurrentUri: false
      preEstablishedRedirectUri: http://localhost:8085/${server.servlet.contextPath}/login/oauth
      clientId: onesaitplatform
      clientSecret: onesaitplatform
      accessTokenUri: http://localhost:18000/controlpanel/oauth/token
      userAuthorizationUri: http://localhost:18000/controlpanel/oauth/authorize
      checkTokenEndpointUrl: http://localhost:18000/controlpanel/oauth/check_token
    resource:
      userInfoUri: http://localhost:21000/oauth-server/user 
logging:
   file.path: ./target/ 
   file.name: ${spring.application.name}
   level:
      com.minsait: INFO 
      org.springframework: ERROR
      org.camunda.bpm: WARN

     