server: ## Config Web Server
   port: 27000
   max-http-header-size: ${MAX_HTTP_HEADER_SIZE}
onesaitplatform:
    authentication:
      oauth:
        osp-keycloak: ${USE_KEYCLOAK}
    camunda:
       admin-user: ${CAMUNDA_ADMIN_USER}
    graylog:
       enabled: ${GRAYLOG_ENABLED}
       host: ${GRAYLOG_HOST}
       port: ${GRAYLOG_PORT}

master:
   datasource:
     hikari:
      jdbc-url: ${CONFIGDBMASTERURL}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}
      maximum-pool-size: ${CONFIGDB_MAX_ACTIVE}
      driver-class-name: ${CONFIGDB_DRIVER}
     

spring: ## General Config
   boot.admin: #Spring Boot Admin Config
      client.url: http://monitoringuiservice:18100/monitoring
      client.instance.service-url: http://bpmengine:${server.port}${server.servlet.contextPath}/
      client.username: ${SBA_USERNAME}
      client.password: ${SBA_SECRET}
   datasource:
     hikari:
      jdbc-url: ${CONFIGDBURL}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}
      connection-timeout: ${DS_MAX_WAIT_MILLIS}
      maximum-pool-size: ${DS_MAX_ACTIVE}
      minimum-idle: ${DS_MIN_IDLE}
      driver-class-name: ${CONFIGDB_DRIVER}
   jpa:
      properties.hibernate.dialect: ${CONFIGDB_DIALECT}
camunda:
   datasource:
      jdbc-url: ${CAMUNDA_DB_URL}${DBADDPROPS}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}
      max-wait: ${CAMUNDA_MAX_WAIT}
      time-between-eviction-runs-millis: ${CAMUNDA_TIME_BETWEEN_EVICTION_RUNS_MILLIS}
      min-evictable-idle-time-millis: ${CAMUNDA_MIN_EVICTABLE_IDLE_TIME_MILLIS}
      max-active: ${CAMUNDA_MAX_ACTIVE}
      initial-size: ${CAMUNDA_INITIAL_SIZE}
      max-idle: ${CAMUNDA_MAX_IDLE}
      min-idle: ${CAMUNDA_MIN_IDLE}
      removeAbandonedTimeout: ${CAMUNDA_REMOVE_ABANDONED_TIMEOUT}
      driver-class-name: ${CONFIGDB_DRIVER}

security:
  oauth2:
    client:
      useCurrentUri: ${OAUTH_USE_DEFAULT_URI}
      preEstablishedRedirectUri: https://${SERVER_NAME}${server.servlet.contextPath}/login/oauth
      clientId: ${OAUTH_CLIENT_ID}
      clientSecret: ${OAUTH_CLIENT_SECRET}
      accessTokenUri: ${OAUTH_SERVER_URL}/oauth/token
      userAuthorizationUri: ${OAUTH_SERVER_URL}/oauth/authorize
      checkTokenEndpointUrl: ${OAUTH_SERVER_URL}/oauth/check_token
    resource:
      userInfoUri: ${OAUTH_SERVER}/user
logging:
   file.path: /var/log/platform-logs
   level:
      org.springframework.security: ${LOG_LEVEL}
      org.camunda.bpm:  ${LOG_LEVEL}
