master: 
   datasource:
      hikari: 
        jdbc-url: jdbc:mysql://localhost:3306/onesaitplatform_master_config?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true
        username: root
        password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
        driver-class-name: com.mysql.cj.jdbc.Driver
        pool-name: master-hikari-pool
        minimum-idle: 1
        maximum-pool-size: 2
        connection-timeout: 10000
    
     
        
      removeAbandoned: true
server: 
   port: 21001    
   servlet:
      contextPath: /systemconfig-init


onesaitplatform: #Config Sofia2 specific
   ontologies:
         schema: 
             ignore-case-properties: true
   init:
      configdb: true
      mongodb: true
      samples: true
      elasticdb: false
      mailconfig: true
      multitenant.update-mode: true
      graylog: false
   database.mongodb:
      database: onesaitplatform_rtdb
      digitaltwin.database: digital_twin  
   database.elasticsearch:
      database: onesaitplatform_rtdb_es
      sql.maxHttpConnections: 10
      sql.maxHttpConnectionsPerRoute: 10
      sql.connectionTimeout.millis: 10000
      sql.connector.http.endpoint: http://localhost:9200
      url: localhost
      port: 9300
   iotbroker.plugable.gateway.kafka.enable: true
   kafka.ksql.enable: false
   webproject:
      rootfolder.path: /usr/local/webprojects/
      baseurl: http://localhost:8087/web/
   controlpanel:
         url: http://localhost:18000/controlpanel
   graylog:
         user: admin
         password: ENC(WOukGj28rhRwzEa3HDCnH2p4vX3Iur8V)
         enabled: false
         host: 127.0.0.1
         port: 12201
         externalUri: http://127.0.0.1:9000
         plugin.auth.path.token: http://localhost:21000/oauth-server/oauth/token
         plugin.auth.path.userinfo: http://localhost:21000/oauth-server/oidc/userinfo
spring:
   ## GENERAL CONFIG
   application.name: systemconfig-init
   ## JPA Config
   datasource:
     hikari:
      jdbc-url: jdbc:mysql://localhost:3306/onesaitplatform_config?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true&nullDatabaseMeansCurrent=true
      username: root
      password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
      connection-timeout: 10000
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 10
      

   jpa:
      ## Hibernate Properties
      # Hibernate ddl auto (create, create-drop, validate, update)
      hibernate.ddl-auto: update
      properties:
        hibernate:
          format_sql: false
          show_sql: false

          
      
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

      
## LOGGING CONF
logging:
   path: ./target/ 
   file: ${spring.application.name}
   level:
      org.springframework: INFO
      com.example.boot.thymeleaf: INFO
      com.minsait: INFO
      org.hibernate: WARN
      org.apache.kafka: ERROR
