master:
   datasource:
      url: ${CONFIGDBMASTERURL}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}
      max-active: ${CONFIGDB_MAX_ACTIVE}
      max-idle: ${CONFIGDB_MAX_IDLE}
     
onesaitplatform:
   flowengine:
      node.path: node
      launcher:
         path: /opt/nodeRed/Flow-Engine-Manager
         logging:
            active: ${ENABLE_NODERED_LOG}
            log: ${NODERED_LOG_PATH}
            retain.days: ${NODERED_LOG_RETAIN_DAYS}
   database.mongodb:
      quasar.connector.http.endpoint: http://${QUASARHOST}:${QUASARPORT}/query/fs/
   database.elasticsearch:
      sql.connector.http.endpoint: http://${ELASTICDBHOST}:${ELASTICDBPORT}
      url: ${ELASTICDBHOST}
      port: 9300
   router.alternativeURL: http://routerservice:20000/router/router/
   audit.global.notify: ${AUDITGLOBALNOTIFY}
   hazelcast.service.discovery.strategy: ${HZ_SERVICE_DISCOVERY_STRATEGY}
   hazelcast.service.discovery.zookeeper.url: ${HZ_ZOOKEEPER_URL}
   analytics.notebook:
      zeppelinHostname: zeppelin

spring:
   datasource:
      url: ${CONFIGDBURL}${DBADDPROPS}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}
      driver-class-name: com.mysql.jdbc.Driver
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1
      time-between-eviction-runs-millis: ${DS_TIME_BETWEEN_EVICTION_RUNS_MILLIS}
      min-evictable-idle-time-millis: ${DS_MIN_EVICTABLE_IDLE_TIME_MILLIS}
      max-wait-millis: ${DS_MAX_WAIT_MILLIS}
      max-wait: ${DS_MAX_WAIT}
      initial-size: ${DS_INITIAL_SIZE}
      max-active: ${DS_MAX_ACTIVE}
      max-idle: ${DS_MAX_IDLE}
      min-idle: ${DS_MIN_IDLE}
      removeAbandoned: ${DS_REMOVE_ABANDONED}
      removeAbandonedTimeout: ${DS_REMOVE_ABANDONED_TIMEOUT}
   boot.admin: #Spring Boot Admin Config
      url: http://monitoringuiservice:18100/monitoring
      client.service-url: http://flowengineservice:${server.port}${server.contextPath}/
   data.mongodb:
      host: ${REALTIMEDBSERVERS}
   elasticsearch.jest:
      uris: http://${ELASTICDBHOST}:${ELASTICDBPORT}
quartz:
    datasource:
      url: ${SCHEDULERDBBURL}${DBADDPROPS}
## LOGGING CONF
logging:
   path: /var/log/platform-logs
