sofia2: #Config Sofia2 specific
   database.elasticsearch:
      sql.connector.http.endpoint: http://elasticdb:9200
      url: elasticdb
      port: 9300

spring:
   elasticsearch.jest:
      uris: http://elasticdb:9200
   datasource:
      url: jdbc:mysql://configdb:3306/onesaitplatform_config?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      password: changeIt!