onesaitplatform: #Config Sofia2 specific
   database.elasticsearch:
      sql.maxHttpConnections: 10
      sql.maxHttpConnectionsPerRoute: 10
      sql.connectionTimeout.millis: 10000
      sql.connector.http.endpoint: http://localhost:9200
      url: localhost
      port: 9300


spring:
   ## GENERAL CONFIG
   application.name: onesaitplatform-persistence-ri
   ## Spring Data Config for MongoDB
   data.mongodb:
      #authentication-database: admin # Authentication database name.
      database: sofia # Database name.
      #field-naming-strategy: # Fully qualified name of the FieldNamingStrategy to use.
      #grid-fs-database: # GridFS database name.
      #host: localhost # Mongo server host. Cannot be set with uri.
      #username: # Login user of the mongo server. Cannot be set with uri. 
      ##password: # Login password of the mongo server. Cannot be set with uri.
      #port: 27017 # Mongo server port. Cannot be set with uri.
      #repositories.enabled: false # Enable Mongo repositories.

      
      #uri: mongodb://localhost/sofia # Mongo database URI. Cannot be set with host, port and credentials.
   
   ## JPA Config
   datasource:
      url: jdbc:mysql://localhost:3306/onesaitplatform_config?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true
      username: root
      password: changeIt!
   jpa:
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            
## LOGGING CONF
logging:
   level:
      org.springframework: INFO
      com.example.boot.thymeleaf: INFO
      com.indra: DEBUG
      org.hibernate: INFO


 