onesaitplatform: #Config Sofia2 specific
   database.elasticsearch:
      sql.maxHttpConnections: 10
      sql.maxHttpConnectionsPerRoute: 10
      sql.connectionTimeout.millis: 10000
      sql.connector.http.endpoint: http://localhost:9200
      url: localhost
      port: 9300
      
master: 
   datasource:
      url: jdbc:mysql://localhost:3306/onesaitplatform_master_config?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true
      username: root
      password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
      driver-class-name: com.mysql.jdbc.Driver
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1      
      
      # Number of ms to wait before throwing an exception if no connection is available.
      max-wait: 10000
      # Maximum number of active connections that can be allocated from this pool at the same time.
      max-active: 2
      initial-size: 1
      max-idle: 2
      min-idle: 1
      removeAbandoned: true
spring:
  application.name: onesaitplatform-persistence-elasticsearch
  datasource:
    url: jdbc:mysql://localhost:3306/onesaitplatform_config?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true
    username: root
    password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
    driver-class-name: com.mysql.jdbc.Driver
    # Validate the connection before borrowing it from the pool.
    test-on-borrow: true
    validation-query: SELECT 1
    test-while-idle: true
    test-on-return: false
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 6000
    max-wait-millis: 10000
    # Number of ms to wait before throwing an exception if no connection is available.
    max-wait: 10000
    # Maximum number of active connections that can be allocated from this pool at the same time.
    initial-size: 10
    max-active: 30
    max-idle: 5
    min-idle: 5
    removeAbandoned: true
            
## LOGGING CONF
logging:
   level:
      org.springframework: INFO
      com.example.boot.thymeleaf: INFO
      com.indra: DEBUG
      org.hibernate: INFO


 