onesaitplatform:
   api-key: ${ADMIN_API_KEY}
   serverless:
     url: https://${SERVER_NAME}/fn
   controlpanel:
     url: http://controlpanelservice:18000/controlpanel
   authentication:
      oauth:
        client:
            accessTokenUri: ${ACCESS_TOKEN_URL}
            userAuthorizationUri: ${AUTHORIZATION_URL}
            checkTokenEndpointUrl: ${CHECK_TOKEN_URL}
            preEstablishedRedirectUri: https://${SERVER_NAME}/controlpanel/login
        resource:
            userInfoUri: ${USERINFO_URL}
        
   
spring:
   datasource:
      url: ${CONFIGDBURL}${DBADDPROPS}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}
      driver-class-name: ${CONFIGDB_DRIVER}
   jpa:
      database-platform: ${CONFIGDB_DIALECT}
 
logging:
   level:
      ROOT: ${ROOT_LOG_LEVEL}
      com.minsait: ${MINSAIT_LOG_LEVEL}
      org.springframework: ${SPRING_LOG_LEVEL}