master:
   datasource:
     hikari:
      jdbc-url: ${CONFIGDBMASTERURL}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}
      maximum-pool-size: ${CONFIGDB_MAX_ACTIVE}
      driver-class-name: ${CONFIGDB_DRIVER}
     
onesaitplatform: #Config onesaitplatform specific
   iotbroker.plugable:
      gateway:
         kafka:
            enable: ${KAFKAENABLED}
            brokers: ${KAFKABROKERS}
            host: ${KAFKAHOST}
            port: ${KAFKAPORT}
   database.elasticsearch.enabled: ${ELASTICSEARCH_ENABLED}
   database.mongodb:
      database: ${REALTIMEDBNAME}
      servers: ${REALTIMEDBSERVERS}
      authenticationDatabase: ${REALTIMEDBAUTHDB}
      useAuth: ${REALTIMEDBUSEAUTH}
      username: ${REALTIMEDBUSER}
      password: ${REALTIMEDBPASS}
      writeConcern: ${REALTIMEDBWRITECONCERN}
      quasar.connector.http.endpoint: http://${QUASARHOST}:${QUASARPORT}/query/fs/
      quasar.maxHttpConnections: ${MAXCONN}
      quasar.maxHttpConnectionsPerRoute: ${MAXCONNROUTE}
   database.hadoop.enabled: ${ENABLEHADOOP}
   database.hdfs:
      url: ${HDFSURL}
      basePath: ${HDFSPATH}
   database.hive:
      url: ${HIVEURL}
      username: ${HIVEUSERNAME}
      password: ${HIVEPASSWORD}
      driverClassName: ${HIVEDRIVERCLASS}
   database.impala:
      url: ${IMPALAURL}
   database.kudu:
      numreplicas: ${KUDUNUMREPLICAS}
      address: ${KUDUURL}
      includeKudutableName: ${INCLUDEKUDUTABLENAME}
      client:
        sessionTimeout: ${KUDUCLIENTSESSIONTIMEOUT}
        flushMode: ${KUDUCLIENTFLUSHMODE}
        prefix: ${KUDUCLIENTIMPALAPREFIX}
        bossThreadPool: ${KUDUCLIENTBOSSTHREADPOOL}
        workerThreadPool: ${KUDUCLIENTWORKERTHREADPOOL}
        operationTimeout: ${KUDUCLIENTOPTIMEOUT}
        adminOperationTimeout: ${KUDUCLIENTADMINOPTIMEOUT}
        socketReadTimeout: ${KUDUCLIENTSOCKETREADTIMEOUT}
   database.timeseries.timezone: ${TIMESERIES_TIMEZONE}
   database.timescaledb:
      enabled: ${TIMESCALE_ENABLED}
      url: ${TIMESCALE_URL}
      user: ${TIMESCALE_USER}
      password: ${TIMESCALE_PASS}
   database.minio:
      access-key: ${MINIO_ROOT_USER}
      secret-key: ${MINIO_ROOT_PASSWORD}
   database.prestodb:
      historicalCatalog: minio
      historicalSchema: default
   audit.global.notify: ${AUDITGLOBALNOTIFY}
   hazelcast.service.discovery.strategy: ${HZ_SERVICE_DISCOVERY_STRATEGY}
   hazelcast.service.discovery.zookeeper.url: ${HZ_ZOOKEEPER_URL}
   router.notifications.pool:
      nodered: ${NOTIFICATION_POOL_NODERED}
      kafka: ${NOTIFICATION_POOL_KAFKA}
      rulesengine: ${NOTIFICATION_POOL_RULESENGINE}
      subscription: ${NOTIFICATION_POOL_SUBSCRIPTION}
      subscription.notificator: ${NOTIFICATION_POOL_SUBSCRIPTION_NOTIFICATOR}
      subscription.attemps: ${NOTIFICATION_SUBSCRIPTION_ATTEMPS}
   urls:
      iotbroker.advice: http://iotbrokerservice:19000/iot-broker/advice
   graylog:
      enabled: ${GRAYLOG_ENABLED}
      host: ${GRAYLOG_HOST}
      port: ${GRAYLOG_PORT}

spring: ## General Config
   boot.admin: #Spring Boot Admin Config
      client.url: http://monitoringuiservice:18100/monitoring
      client.instance.service-url: http://routerservice:${server.port}${server.servlet.contextPath}/
      client.username: ${SBA_USERNAME}
      client.password: ${SBA_SECRET}
   datasource:
     hikari:
      jdbc-url: ${CONFIGDBURL}${DBADDPROPS}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}
      connection-timeout: ${DS_MAX_WAIT_MILLIS}
      maximum-pool-size: ${DS_MAX_ACTIVE}
      minimum-idle: ${DS_MIN_IDLE}
      driver-class-name: ${CONFIGDB_DRIVER}
   data.mongodb:
      host: ${REALTIMEDBSERVERS}
   elasticsearch.jest:
      uris: http://${ELASTICDBHOST}:${ELASTICDBPORT}
   jpa:
      properties.hibernate.dialect: ${CONFIGDB_DIALECT}

## LOGGING CONF
logging:
   file.path: /var/log/platform-logs
   level:
      com.minsait: ${OP_LOG_LEVEL}
      org.springframework.boot: ${OP_LOG_LEVEL}
