onesaitplatform: #Config onesaitplatform specific
   iotbroker.plugable:
      gateway:
         kafka:
            enable: ${KAFKAENABLED}
            host: ${KAFKAHOST}
            port: ${KAFKAPORT}
   database.elasticsearch:
      sql.connector.http.endpoint: http://${ELASTICDBHOST}:${ELASTICDBPORT}
      url: ${ELASTICDBHOST}
   database.mongodb:
      database: ${REALTIMEDBNAME}
      servers: ${REALTIMEDBSERVERS} 
      authenticationDatabase: ${REALTIMEDBAUTHDB}               
      useAuth: ${REALTIMEDBUSEAUTH}
      username: ${REALTIMEDBUSER}
      password: ${REALTIMEDBPASS}
      writeConcern: ${REALTIMEDBWRITECONCERN}     
      quasar.connector.http.endpoint: http://${QUASARHOST}:${QUASARPORT}/query/fs/ 
      quasar.maxHttpConnections: ${MAXCONN}
      quasar.maxHttpConnectionsPerRoute: ${MAXCONNROUTE}
   database.hadoop.enabled: ${ENABLEHADOOP}
   database.hdfs:
      url: ${HDFSURL}
      basePath: ${HDFSPATH}
   database.hive:
      url: ${HIVEURL}
      username: ${HIVEUSERNAME}
      password: ${HIVEPASSWORD}
      driverClassName: ${HIVEDRIVERCLASS}
   database.impala:
      url: ${IMPALAURL}
   database.kudu:
      numreplicas: ${KUDUNUMREPLICAS}
      address: ${KUDUURL}
      includeKudutableName: ${INCLUDEKUDUTABLENAME}
      client:
        sessionTimeout: ${KUDUCLIENTSESSIONTIMEOUT}
        flushMode: ${KUDUCLIENTFLUSHMODE}
        prefix: ${KUDUCLIENTIMPALAPREFIX}
        bossThreadPool: ${KUDUCLIENTBOSSTHREADPOOL}
        workerThreadPool: ${KUDUCLIENTWORKERTHREADPOOL}
        operationTimeout: ${KUDUCLIENTOPTIMEOUT}
        adminOperationTimeout: ${KUDUCLIENTADMINOPTIMEOUT}
        socketReadTimeout: ${KUDUCLIENTSOCKETREADTIMEOUT}
   database.timeseries.timezone: ${TIMESERIES_TIMEZONE}

   audit.global.notify: ${AUDITGLOBALNOTIFY}
   hazelcast.service.discovery.strategy: ${HZ_SERVICE_DISCOVERY_STRATEGY}
   hazelcast.service.discovery.zookeeper.url: ${HZ_ZOOKEEPER_URL}

   
spring: ## General Config  
   boot.admin: #Spring Boot Admin Config    
      url: http://monitoringuiservice:18100/monitoring    
      client.service-url: http://routerservice:${server.port}${server.contextPath}/ 
   datasource: ## JPA Config
      url: ${JDBCPROTOCOL}//${CONFIGDBSERVERS}/onesaitplatform_config?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true${DBADDPROPS}
   data.mongodb:
      host: ${REALTIMEDBSERVERS}      
   elasticsearch.jest:
      uris: http://${ELASTICDBHOST}:${ELASTICDBPORT}      
            
## LOGGING CONF
logging:
   path: /var/log/platform-logs
   level:
      com.minsait: ${OP_LOG_LEVEL}
      org.springframework.boot: ${OP_LOG_LEVEL}