modules:
   engine:
      -  
         name: Api Manager 
         namespace: onesait-platform
         pod: apimanagerservice
      -  
         name: Flow Engine 
         namespace: onesait-platform
         pod: flowengineservice
      -  
         name: Rules Engine 
         namespace: onesait-platform
         pod: rules-engine-service
      -  
         name: Identity Manager 
         namespace: onesait-platform
         pod: oauthservice
      -  
         name: Elastic DB 
         namespace: onesait-platform
         pod: elasticdb
      -  
         name: Realtime DB
         namespace: onesait-platform
         pod: realtimedb
      -  
         name: Semantic Broker 
         namespace: onesait-platform
         pod: routerservice	
      -  
         name: BPM Engine 
         namespace: onesait-platform
         pod: bpmengine	
      -  
         name: Control Panel
         namespace: onesait-platform
         pod: controlpanelservice
      -  
         name: Log Centralizer
         namespace: onesait-platform
         pod: log-centralizer
      -  
         name: Kafka
         namespace: onesait-platform
         pod: kafkaservice
      -   
         name: Monitoring UI
         namespace: onesait-platform
         pod: monitoringuiservice
      -  
         name: Digital Broker 
         namespace: onesait-platform
         pod: iotbrokerservice
      -  
         name: Gravitee Gateway
         namespace: onesait-platform
         pod: graviteegatewayservice
   intelligence:
      -  
         name: Dataflow 
         namespace: onesait-platform
         pod: streamsets
      -  
         name: Notebooks 
         namespace: onesait-platform
         pod: zeppelin
      -  
         name: Data Refiner 
         namespace: onesait-platform
         pod: datacleanerservice
      -  
         name: Dashboard Engine 
         namespace: onesait-platform
         pod: dashboardengineservice	
      -  
         name: Report Engine 
         namespace: onesait-platform
         pod: reportengine	
      -  
         name: Open Data Portal 
         namespace: onesait-platform
         pod: ckanservice
   things:
      -  
         name: Digital Twin Broker 
         namespace: onesait-platform
         pod: digitaltwinbrokerservice