bootstrap.servers: kafkaservice:9095
group.id: ontologyGroup
key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
key.serializer: org.apache.kafka.common.serialization.StringSerializer
value.serializer: org.apache.kafka.common.serialization.StringSerializer
max.poll.records: 50
metadata.max.age.ms: 500
security.protocol: SASL_PLAINTEXT
sasl.mechanism: PLAIN
sasl.jaas.config: ENC(40rW7K9ZXrDdTY6l7lvdj4bjwfnpi6gVHoK2N+r+C9mOrxlcGk5nDSS+8E9MN35du6hh9l71woRZ47TTEc5e7tcv5ojbBgdcp4PMTIXp+3rJMkFo64Xr3UirJ8wDmTXEaFU9rS5UR2EjeP0IUTLUC0p+ZecmU/LJ)
