#MailGun Config for SMTP
mail:
  host: to_be_configured
  port: 000
  username: ENC(username_encrypted)
  password: ENC(password_encrypted)
  smtp:
     auth: true
     starttls_enable: false
     starttls_required: false
     timeout: 5000
     connectiontimeout: 5000
     writetimeout: 5000
     from: mail@mailserver.com
