#MailGun Config for SMTP
mail:
  host: in-v3.mailjet.com
  port: 587
  username: ENC(I38nqFtz1KCaYtvAv+Ik9PSvzSwYcrxiZzEnI+EdjR/gTcIYXQUSRDBn4fUVYhEg)
  password: ENC(VVgQk6vcHM/+wAlc008HXbpKr6tArOiFM4Vq3OVflqcowkRGWK5InjM/Bg3/cYQg)
  smtp:
     auth: true
     starttls_enable: false
     starttls_required: false
     timeout: 5000
     connectiontimeout: 5000
     writetimeout: 5000
     from: online@onesaitplatform.com
