#MailGun Config for SMTP
mail:
  host: in-v3.mailjet.com
  port: 587
  username: ENC(VZ6x3J/+ijH6iR+uUo3Yk0Q3ucmz+ImJWNNQQgKTdZCK+csfKddLUaEMBDbT9I+k)
  password: ENC(MXchpQGKyY2TTHRyEZDhP0gUtzc4a+en8zVU0hd0Uf+tcnPOfioCCwuzKEwgOJx8)
  smtp:
     auth: true
     starttls_enable: false
     starttls_required: false
     timeout: 5000
     connectiontimeout: 5000
     writetimeout: 5000
     from: online@onesaitplatform.com
