urls: ['https://development.onesaitplatform.com/web/map_project_viewer/vue', 'https://development.onesaitplatform.com/web/map_project_viewer/angular/']
descriptions: ['viewer over vue framework', 'viewer over angular framework']