onesaitplatform:
  env:
    database:
      nebula-hosts: localhost:9669
      nebula-pool-size: 10
      execution-timeout: !!java.lang.Long 10000
      queries-limit: 2000
      mongodb-servers: localhost:27017
      mongodb-database: onesaitplatform_rtdb
      mongodb-socket-timeout: 5000
      mongodb-connect-timeout: 30000
      mongodb-max-wait-time: 5000
      mongodb-pool-size: 10
      mongodb-read-from-secondaries: false
      mongodb-read-preference: secondaryPreferred
      mongodb-write-concern: UNACKNOWLEDGED
      mongodb-ssl-enabled: false
      mongodb-use-quasar: false
      mongodb-use-legacysql: false
      mongodb-quasar-timeout: 10000
      mongodb-quasar-compile: true
      mongodb-quasar-allow-mapreduce: true
      elasticsearch:
        sql:
          endpoint: http://localhost:9200
          #elasticSearch with nlpcn
          queryPath: /_nlpcn/sql
          baseQueryObject: sql 
          #Opendistro SQL
          #queryPath: /_opendistro/_sql?format=json
          #baseQueryObject: query
        dump:
          path: /tmp/export/
          elasticDumpCmd: S:/node_modules/.bin/elasticdump.cmd
        enabled: true
        servers:
          -
            host: localhost
            port: 9200
            protocol: http
        defaults:
          replicas: 0
          shards: 5
    files:
      allowed-extensions: jasper
      max-size: !!java.lang.Long 60000000
    iotbroker:
      session-expiration: !!java.lang.Long 600000
    audit:
      ignore: false
      hash: false
      signed: false
      keystorePath: /usr/local/add_keystore.p12
      keystorePassword: ENC(MXchpQGKyY2TTHRyEZDhP0gUtzc4a+en8zVU0hd0Uf+tcnPOfioCCwuzKEwgOJx8)
    controlpanel:
      maxSessionsPerUser: 10
      password-pattern: (?=^.{10,255}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$