onesaitplatform:
  env:
    database:
      nebula-hosts: graphd:9669
      nebula-pool-size: 10
      execution-timeout: !!java.lang.Long ${RTDB_EXECUTION_TIMEOUT}
      queries-limit: ${RTDB_QUERIES_LIMIT}
      mongodb-servers: ${REALTIMEDBSERVERS}
      mongodb-database: ${REALTIMEDBNAME}
      mongodb-socket-timeout: ${MONGO_SOCKET_TIMEOUT}
      mongodb-connect-timeout: ${MONGO_CONNECT_TIMEOUT}
      mongodb-max-wait-time: ${MONGO_WAIT_TIME}
      mongodb-pool-size: ${MONGO_POOL_SIZE}
      mongodb-read-from-secondaries: false
      mongodb-read-preference: secondaryPreferred
      mongodb-write-concern: ${REALTIMEDBWRITECONCERN}
      mongodb-ssl-enabled: ${MONGO_SSL_ENABLED}
      mongodb-use-quasar: ${MONGO_USE_QUASAR}
      mongodb-use-legacysql: false
      mongodb-quasar-timeout: 10000
      mongodb-quasar-compile: true
      mongodb-quasar-allow-mapreduce: true
      elasticsearch:
        username: admin
        password: admin        
        sql:
          endpoint: http://elasticdb:9200
          queryPath: /_nlpcn/sql
          baseQueryObject: sql 
        dump:
          path: /tmp/export/
          elasticDumpCmd: S:/node_modules/.bin/elasticdump.cmd
        enabled: true
        servers:
          -
            host: elasticdb
            port: 9200
            protocol: http
        defaults:
          replicas: 0
          shards: 5
    files:
      allowed-extensions: jasper
      max-size: !!java.lang.Long 60000000
    iotbroker:
      session-expiration: !!java.lang.Long 600000
    audit:
      ignore: false
      hash: false
      signed: false
      keystorePath: /usr/local/add_keystore.p12
      keystorePassword: ENC(MXchpQGKyY2TTHRyEZDhP0gUtzc4a+en8zVU0hd0Uf+tcnPOfioCCwuzKEwgOJx8)
    controlpanel:
      maxSessionsPerUser: 10
      password-pattern: (?=^.{10,255}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$