master:
   datasource:
     hikari:
      jdbc-url: ${CONFIGDBMASTERURL}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}

spring:
  boot.admin: #Spring Boot Admin Config    
    client.url: http://monitoringuiservice:18100/monitoring  
    client.instance.service-url: http://videobrokerservice:${server.port}${server.servlet.contextPath}/ 
  datasource:
     hikari:
      jdbc-url: ${CONFIGDBURL}${DBADDPROPS}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}
      connection-timeout: ${DS_MAX_WAIT_MILLIS}
      maximum-pool-size: ${DS_MAX_ACTIVE}
      minimum-idle: ${DS_MIN_IDLE}

onesaitplatform:
  kafka:
    enable: ${KAFKAENABLED}
    brokers: ${KAFKABROKERS}
    host: ${KAFKAHOST}
    port: ${KAFKAPORT}  
    user: ${KAFKAUSER}
    password: ${KAFKAPASSWORD}
    partitions: 10
    replication: 1
  audit.global.notify: ${AUDITGLOBALNOTIFY}   
  hazelcast.service.discovery.strategy: ${HZ_SERVICE_DISCOVERY_STRATEGY} 
  hazelcast.service.discovery.zookeeper.url: ${HZ_ZOOKEEPER_URL}
  graylog:
    enabled: ${GRAYLOG_ENABLED}
    host: ${GRAYLOG_HOST}
    port: ${GRAYLOG_PORT}

## LOGGING CONF
logging:
   path: /var/log/platform-logs 
   level:
      com.minsait: ${OP_LOG_LEVEL}
      org.springframework.boot: ${OP_LOG_LEVEL}
