onesaitplatform:
   secure.cookie: true
   authentication:
      oauth:
        osp-keycloak: ${USE_KEYCLOAK}
      configdb:
        acl:
          enabled: ${CONFIGDB_ACL_ENABLED}
          list: ${CONFIGDB_ACL_LIST}
   database.mongodb:
      quasar.connector.http.endpoint: http://${QUASARHOST}:${QUASARPORT}/query/fs/
   database.elasticsearch:
      sql.connector.http.endpoint: http://${ELASTICDBHOST}:${ELASTICDBPORT}
      url: ${ELASTICDBHOST}
      port: 9300
   router.alternativeURL: http://routerservice:20000/router/router/
   audit.global.notify: ${AUDITGLOBALNOTIFY}
   hazelcast.service.discovery.strategy: ${HZ_SERVICE_DISCOVERY_STRATEGY}
   hazelcast.service.discovery.zookeeper.url: ${HZ_ZOOKEEPER_URL}
   metrics:
      collector.endpoint: http://routerservice:20000/router/metrics-collector/refresh
      enabled: ${ENABLE_METRICS}
   graylog:
      enabled: ${GRAYLOG_ENABLED}
      host: ${GRAYLOG_HOST}
      port: ${GRAYLOG_PORT}
   secure.cookie: true

master:
   datasource:
     hikari:
      jdbc-url: ${CONFIGDBMASTERURL}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}
      maximum-pool-size: ${CONFIGDB_MAX_ACTIVE}

spring:
   datasource:
     hikari:
      jdbc-url: ${CONFIGDBURL}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}
      connection-timeout: ${DS_MAX_WAIT_MILLIS}
      maximum-pool-size: ${DS_MAX_ACTIVE}
      minimum-idle: ${DS_MIN_IDLE}
      
   boot.admin: #Spring Boot Admin Config
      client.url: http://monitoringuiservice:18100/monitoring
      client.instance.service-url: http://apimanagerservice:${server.port}${server.servlet.contextPath}/
      client.username: ${SBA_USERNAME}
      client.password: ${SBA_SECRET}
   data.mongodb:
      host: ${REALTIMEDBSERVERS}
   elasticsearch.jest:
      uris: http://${ELASTICDBHOST}:${ELASTICDBPORT}

## LOGGING CONF
logging:
   path: /var/log/platform-logs
   level:
      com.minsait: ${OP_LOG_LEVEL}
      org.springframework.boot: ${OP_LOG_LEVEL}
