version: '2'
services:
  #registryui:
  #  scale: 1
  #  start_on_create: false
  oauthservice:
    scale: 1
    start_on_create: false
  streamsets:
    scale: 1
    start_on_create: false
  schedulerdb:
    scale: 1
    start_on_create: true
  configinit:
    scale: 1
    start_on_create: false
  apimanagerservice:
    scale: 1
    start_on_create: false
  digitaltwinbrokerservice:
    scale: 1
    start_on_create: false
  cacheservice:
    scale: 1
    start_on_create: false
  flowengineservice:
    scale: 1
    start_on_create: false
  controlpanelservice:
    scale: 1
    start_on_create: false
  zookeeper:
    scale: 1
    start_on_create: false
  devicesimulator:
    scale: 1
    start_on_create: false
  zeppelin:
    scale: 1
    start_on_create: false
  configdb:
    scale: 1
    start_on_create: true
  rtdbmaintainerservice:
    scale: 1
    start_on_create: false
  iotbrokerservice:
    scale: 1
    start_on_create: false
  loadbalancerservice:
    scale: 1
    start_on_create: false
  quasar:
    scale: 1
    start_on_create: false
  monitoringuiservice:
    scale: 1
    start_on_create: false
  haproxy:
    scale: 1
    start_on_create: false
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: tcp
        service: iotbrokerservice
        source_port: 1883
        target_port: 1883
      - priority: 2
        protocol: tcp
        service: iotbrokerservice
        source_port: 8883
        target_port: 8883
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  dashboardengineservice:
    scale: 1
    start_on_create: false
  routerservice:
    scale: 1
    start_on_create: false
  realtimedb:
    scale: 1
    start_on_create: true
