master:
   datasource:
     hikari:
      jdbc-url: ${CONFIGDBMASTERURL}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}
      maximum-pool-size: ${CONFIGDB_MAX_ACTIVE}
     
onesaitplatform:
   multitenancy:
      enabled: ${MULTITENANCY_ENABLED}
   database.mongodb:
      quasar.connector.http.endpoint: http://${QUASARHOST}:${QUASARPORT}/query/fs/
   database.elasticsearch:
      sql.connector.http.endpoint: http://${ELASTICDBHOST}:${ELASTICDBPORT}
      url: ${ELASTICDBHOST}
      port: 9300
   hazelcast.service.discovery.strategy: ${HZ_SERVICE_DISCOVERY_STRATEGY}
   hazelcast.service.discovery.zookeeper.url: ${HZ_ZOOKEEPER_URL}      
   audit.global.notify: ${AUDITGLOBALNOTIFY}
   password.pattern: (?=^.{10,128}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$
   authentication:
      configdb:
        acl:
          enabled: ${CONFIGDB_ACL_ENABLED}
          list: ${CONFIGDB_ACL_LIST}

ldap:
  url: ${LDAP_URL}
  base: ${LDAP_BASE_DN}
  ignorepartialresult: ${LDAP_IGNORE_PARTIAL_RESULT}
  username: ${LDAP_ADMIN_DN}
  password: ${LDAP_ADMIN_PASSWORD}
  defaultRole: ${LDAP_DEFAULT_ROLE}
  platformRolesGroup:
      administrator: ${LDAP_ADMINISTRATOR_DN}
      datascientist: ${LDAP_ANALYTICS_DN}
      dataviewer: ${LDAP_DATAVIEWER_DN}
      developer: ${LDAP_DEVELOPER_DN}
      devops: ${LDAP_DEVOPS_DN}
      operations: ${LDAP_OPERATIONS_DN}
      partner: ${LDAP_PARTNER_DN}
      platformAdmin: ${LDAP_PLATFORM_ADMIN_DN}
      sysAdmin:  ${LDAP_SYS_ADMIN_DN}
      user:  ${LDAP_USER_DN}
  attributesMap:
     userId: ${LDAP_USERID_ATT}
     mail: ${LDAP_MAIL_ATT}
     cn: ${LDAP_CN_ATT}
     groupOfNames: ${LDAP_GROUP_OF_NAMES_ATT}
  rolesmemberattribute: ${LDAP_ROLES_MEMBER_ATT}


spring:
   datasource:
     hikari:
      jdbc-url: ${CONFIGDBURL}${DBADDPROPS}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}
      connection-timeout: ${DS_MAX_WAIT_MILLIS}
      maximum-pool-size: ${DS_MAX_ACTIVE}
      minimum-idle: ${DS_MIN_IDLE}
   boot.admin: #Spring Boot Admin Config
      client.url: http://monitoringuiservice:18100/monitoring
      client.instance.service-url: http://oauthservice:${server.port}${server.servlet.contextPath}/
   data.mongodb:
      host: ${REALTIMEDBSERVERS}
   elasticsearch.jest:
      uris: http://${ELASTICDBHOST}:${ELASTICDBPORT}
quartz:
    datasource:
      hikari.jdbc-url: ${SCHEDULERDBBURL}${DBADDPROPS}

## LOGGING CONF
logging:
   path: /var/log/platform-logs
