server: ## Config Web Server
   port: 18400
   servlet.contextPath: /report-engine
   max-http-header-size: 10000000
   tomcat:
      access_log_enabled: true
      basedir: target/tomcat
   jetty.max-http-post-size: 20000000
master: 
   datasource:
      hikari: 
        jdbc-url: jdbc:mysql://localhost:3306/onesaitplatform_master_config?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true
        username: root
        password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
        driver-class-name: com.mysql.cj.jdbc.Driver
        pool-name: master-hikari-pool
        minimum-idle: 3
        maximum-pool-size: 10
        connection-timeout: 10000
        
spring: ## General Config  
   boot.admin: #Spring Boot Admin Config   
      url: http://localhost:18100/monitoring
      username: operations
      password: ENC(2Xd2AOD2NrMaWs915/st8C4ILo3qlHXv)
      client.metadata.user.name: ${spring.boot.admin.username}
      client.metadata.user.password: ${spring.boot.admin.password}
   main.allow-bean-definition-overriding: true
   application.name: onesaitplatform-report-engine
   datasource:
     hikari:
      jdbc-url: jdbc:mysql://localhost:3306/onesaitplatform_config?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true&nullDatabaseMeansCurrent=true
      username: root
      password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
      connection-timeout: 10000
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 10
     
   jpa:
      open-in-view: false
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.ddl-auto: validate
      properties:
        hibernate:
          format_sql: false
          show_sql: false
          
logging:
   path: ./target/ 
   file: ${spring.application.name}
   level:
      com.minsait: INFO 
      org.springframework.security: INFO
      org.camunda.bpm: WARN

     