server: ## Config Web Server
   port: 18400
   contextPath: /report-engine
   max-http-header-size: 10000000
   tomcat:
      access_log_enabled: true
      basedir: target/tomcat
   jetty.max-http-post-size: 20000000

      
master: 
   datasource:
      url: jdbc:mysql://localhost:3306/onesaitplatform_master_config?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true
      username: root
      password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
      driver-class-name: com.mysql.jdbc.Driver
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1
      validationQueryTimeout: 5
      # Number of ms to wait before throwing an exception if no connection is available.
      max-wait: 10000
      # Maximum number of active connections that can be allocated from this pool at the same time.
      max-active: 2
      initial-size: 1
      max-idle: 2
      min-idle: 1
      removeAbandoned: true
spring: ## General Config  
   boot.admin: #Spring Boot Admin Config   
      url: http://localhost:18100/monitoring
      username: operations
      password: ENC(2Xd2AOD2NrMaWs915/st8C4ILo3qlHXv)
      client.metadata.user.name: ${spring.boot.admin.username}
      client.metadata.user.password: ${spring.boot.admin.password}
   main.allow-bean-definition-overriding: true
   application.name: onesaitplatform-report-engine
   datasource: ## JPA Config
      url: jdbc:mysql://localhost:3306/onesaitplatform_config?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true&nullDatabaseMeansCurrent=true
      username: root
      password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
      driver-class-name: com.mysql.jdbc.Driver
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1      
      validationQueryTimeout: 5
      max-wait: 10000
      max-active: 30
      initial-size: 10
      max-idle: 30
      min-idle: 10
      removeAbandoned: true
     
   jpa:
      open-in-view: false
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.ddl-auto: validate
      properties:
        hibernate:
          format_sql: false
          show_sql: false
          
logging:
   path: ./target/ 
   file: ${spring.application.name}
   level:
      com.minsait: INFO 
      org.springframework.security: INFO
      org.camunda.bpm: WARN

     