server: ## Config Web Server
   port: 18400
onesaitplatform:
   database.mongodb:
      authenticationDatabase: ${REALTIMEDBAUTHDB}
      useAuth: ${REALTIMEDBUSEAUTH}
      username: ${REALTIMEDBUSER}
      password: ${REALTIMEDBPASS}

master:
   datasource:
     hikari:
      jdbc-url: ${CONFIGDBMASTERURL}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}
      
     

spring: ## General Config
   boot.admin: #Spring Boot Admin Config
      client.url: http://monitoringuiservice:18100/monitoring
      client.instance.service-url: http://reportengine:${server.port}${server.servlet.contextPath}/
   datasource:
     hikari:
      jdbc-url: ${CONFIGDBURL}${DBADDPROPS}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}
      connection-timeout: ${DS_MAX_WAIT_MILLIS}
      maximum-pool-size: ${DS_MAX_ACTIVE}
      minimum-idle: ${DS_MIN_IDLE}

logging:
   path: /var/log/platform-logs
   level:
      org.springframework.security: ${LOG_LEVEL}
      org.camunda.bpm:  ${LOG_LEVEL}
