apimanager: https://development.onesaitplatform.com/api-manager
oauth-server: https://odeo-int-test-onesait.odeo-ocp.com/oauth-server
controlpanel: https://development.onesaitplatform.com/controlpanel
microservice: https://development.onesaitplatform.com/restaurants
host: http://localhost:18000/

vertical: onesaitplatform
client-id: OdeoRealm
client-secret: onesaitplatform
username: 567217fb27dd33a65db807c3158e6f29109eed7a337e853ce24e1e9d8ce2b17b
password: Passw0rd!!
logging:
   level:
      com.minsait: INFO
      org.springframework: INFO
      org.eclipse.jetty: ERROR
      
      
   