apimanager: https://development.onesaitplatform.com/api-manager
oauth-server: https://10.22.205.151/oauth-server
controlpanel: https://development.onesaitplatform.com/controlpanel
microservice: https://development.onesaitplatform.com/restaurants


vertical: Engine
client-id: RealmEssentials
client-secret: onesaitplatform
username: administrator
password: OpenP2019!
logging:
   level:
      com.minsait: INFO
      org.springframework: INFO
      org.eclipse.jetty: ERROR
      
      
   