##--spring.config.name=controlpanel
##security.require_ssl: true
server: ## Config Web Server
   #ssl:
   #   key-store-type: JKS
    #  key-store-password: Changed!
   #   key-store: classpath:keystore.jks
    #  key-alias: tomcat
   session.cookie.name : APPSESSIONID
   max-http-header-size: 10000000
   port: 18100
   servlet.contextPath: /monitoring
   tomcat:
      access_log_enabled: true
      basedir: target/tomcat
      
master: 
   datasource:
      hikari: 
        jdbc-url: jdbc:mysql://localhost:3306/onesaitplatform_master_config?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true
        username: root
        password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
        driver-class-name: com.mysql.cj.jdbc.Driver
        pool-name: master-hikari-pool
        minimum-idle: 1
        maximum-pool-size: 2
        connection-timeout: 10000
     
onesaitplatform: #Config onesait Platform specific
   encryption:
      key: ENC(VYVseIUh5xiRd8ws0prbEAg6bGq7vmbfi3gkM65HECy+YPbjz4f49w==)
      iteration-count: 5
   environment.name: local
   authentication:
      oauth:
        osp-keycloak: false
      provider: configdb
      configdb:
        acl:
          enabled: false
          list: administrator,analytics,dataviewer,demo_developer,demo_user,developer,operations,partner,sysadmin,user
   reminder:
      periodInMins: 3
      eachInMs: 300000
      enabled: false
      statuses: DOWN,OFFLINE
   secure:
      cookie: false
   graylog:
      enabled: false
      host: 127.0.0.1
      port: 12201

## Config Reference      
spring: ## General Config  
   application.name: onesaitplatform-monitoring-ui
   boot.admin: #Spring Boot Admin Config    
      routes.endpoints: env,metrics,trace,dump,jolokia,info,configprops,logfile,refresh,loggers
      monitor.period: 120000
      monitor.status-lifetime: 120000
      monitor.connect-timeout: 30000
      monitor.read-timeout: 30000     
      notify.mail.enabled: false
      notify.mail.to: support@onesaitplatform.com
      notify.mail.from: onesaitplatform@gmail.com      
      notify.mail.text: "ENV:#{onesaitplatform.environment.name} App:#{application.name} (#{application.id}) is #{to.status}"
      ui.title: Monitoring UI
      ui.brand: "<img src='assets/img/icon-spring-boot-admin.svg'><span>Monitoring UI</span>"
      #Not autoregister as Spring Boot Admin client
      # username: operations
      # password: changeIt!
      # client.metadata.user.name: ${spring.boot.admin.username}
      # client.metadata.user.password: $spring.boot.admin.password} 
   datasource:
     hikari:
      jdbc-url: jdbc:mysql://localhost:3306/onesaitplatform_config?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true&nullDatabaseMeansCurrent=true
      username: root
      password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
      connection-timeout: 10000
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 10
         
   jpa:
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      # Hibernate ddl auto (create, create-drop, validate, update)
      hibernate.ddl-auto: validate
#  mail: ##Mail configuration
   #  host: smtp.gmail.com
   #  username: onesaitplatform@gmail.com
   #  password: 2Octubre2018!
   #  port: 587
   #  properties.mail.smtp.auth: true
   #  properties.mail.smtp.starttls.enable: true

management.security.roles : ROLE_ADMINISTRATOR
security:
  basic:
    enabled: false
  oauth2:
    client:
      useCurrentUri: false
      preEstablishedRedirectUri: http://localhost:18100/${server.servlet.contextPath}/login/oauth
      clientId: onesaitplatform
      clientSecret: onesaitplatform
      accessTokenUri: http://localhost:21000/oauth-server/oauth/token
      userAuthorizationUri: http://localhost:21000/oauth-server/oauth/authorize
    resource:
      userInfoUri: http://localhost:21000/oauth-server/user
      checkTokenEndpoint: http://localhost:21000/oauth-server/oauth/check_token
          

## LOGGING CONF
logging:
   path: ./target/ 
   file: ${spring.application.name}
   level:
      com.minsait: INFO 
      org.springframework: ERROR
      de.codecentric: ERROR
      root: ERROR
