version: "2"

services:
  postgis:
    image: kartoza/postgis:12.0
    container_name: postgis
    networks:
      - datanetwork
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - POSTGRES_DB=gis
    restart: on-failure
  geoserver:
    image: onesaitplatform/geoserver:latest
    build: .
    container_name: geoserver
    networks:
      - datanetwork
    environment:
      - PG_HOSTNAME=postgis
      - PG_PORT=5432
      - PG_USERNAME=docker
      - PG_PASSWORD=docker
      - PG_DATABASE=gis
    ports:
      - "18080:8080"
    restart: on-failure
    links:
     - "postgis:postgis"
networks:
  datanetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
