spring:
   datasource:  
      url: ${JDBCPROTOCOL}//${CONFIGDBSERVERS}/onesaitplatform_config?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true${DBADDPROPS}
   boot.admin: #Spring Boot Admin Config    
      url: http://monitoringuiservice:18100/monitoring
      client.service-url: http://digitaltwinbrokerservice:${server.port}${server.contextPath}/  
      connect-timeout: 120000
      read-timeout: 150000
   data.mongodb:
      host: ${REALTIMEDBSERVERS} 
   elasticsearch.jest:
      uris: http://${ELASTICDBHOST}:${ELASTICDBPORT}        
onesaitplatform:
  database.mongodb:
    database: ${REALTIMEDBNAME}
    servers: ${REALTIMEDBSERVERS} 
    authenticationDatabase: ${REALTIMEDBAUTHDB}               
    useAuth: ${REALTIMEDBUSEAUTH}
    username: ${REALTIMEDBUSER}
    password: ${REALTIMEDBPASS}
    writeConcern: ${REALTIMEDBWRITECONCERN}     
  database.elasticsearch:
    sql.connector.http.endpoint: http://${ELASTICDBHOST}:${ELASTICDBPORT}
    url: ${ELASTICDBHOST}
    port: 9300
  router.alternativeURL: http://routerservice:20000/router/router/  
  audit.global.notify: ${AUDITGLOBALNOTIFY}
  hazelcast.service.discovery.strategy: ${HZ_SERVICE_DISCOVERY_STRATEGY}
  hazelcast.service.discovery.zookeeper.url: ${HZ_ZOOKEEPER_URL}
    
## LOGGING CONF
logging:
   path: /var/log/platform-logs 