master:
   datasource:
     hikari:
      jdbc-url: ${CONFIGDBMASTERURL}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}
      maximum-pool-size: ${CONFIGDB_MAX_ACTIVE}
     
spring:
   datasource:
     hikari:
      jdbc-url: ${CONFIGDBURL}${DBADDPROPS}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}
      connection-timeout: ${DS_MAX_WAIT_MILLIS}
      maximum-pool-size: ${DS_MAX_ACTIVE}
      minimum-idle: ${DS_MIN_IDLE}
   boot.admin: #Spring Boot Admin Config
      client.url: http://monitoringuiservice:18100/monitoring
      client.instance.service-url: http://digitaltwinbrokerservice:${server.port}${server.servlet.contextPath}/
   data.mongodb:
      host: ${REALTIMEDBSERVERS}
   elasticsearch.jest:
      uris: http://${ELASTICDBHOST}:${ELASTICDBPORT}
onesaitplatform:
  database.mongodb:
    database: ${REALTIMEDBNAME}
    servers: ${REALTIMEDBSERVERS}
    authenticationDatabase: ${REALTIMEDBAUTHDB}
    useAuth: ${REALTIMEDBUSEAUTH}
    username: ${REALTIMEDBUSER}
    password: ${REALTIMEDBPASS}
    writeConcern: ${REALTIMEDBWRITECONCERN}
  database.elasticsearch:
    sql.connector.http.endpoint: http://${ELASTICDBHOST}:${ELASTICDBPORT}
    url: ${ELASTICDBHOST}
    port: 9300
  router.alternativeURL: http://routerservice:20000/router/router/
  audit.global.notify: ${AUDITGLOBALNOTIFY}
  hazelcast.service.discovery.strategy: ${HZ_SERVICE_DISCOVERY_STRATEGY}
  hazelcast.service.discovery.zookeeper.url: ${HZ_ZOOKEEPER_URL}

## LOGGING CONF
logging:
   path: /var/log/platform-logs
