server: ## Config Web Server
   port: 23000
   servlet.contextPath: /sparklauncher
   tomcat:
      access_log_enabled: true
      basedir: target/tomcat
   jetty.max-http-form-post-size: 20000000



#hawtio.authenticationEnabled: false
#hawtio.offline: true

master:
   datasource:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/onesaitplatform_master_config?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true
        username: root
        password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph)
        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:postgresql://localhost:5432/onesaitplatform_master_config
#        username: postgres
#        password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph)
#        driver-class-name: org.postgresql.Driver
        pool-name: master-hikari-pool
        minimum-idle: 1
        maximum-pool-size: 2
        connection-timeout: 10000

onesaitplatform: #Config onesaitplatform specific
   audit.global.notify: true
   apimanager:
      cacheable: false
   database.minio:
      access-key: ENC(d6bDYa5aGMyXndGA0edIGWFtcw3UygXi)
      secret-key: ENC(kV79KowPOv0J8QGeQ6iSQcFUqoZalNVj)
   graylog:
      enabled: false
      host: 127.0.0.1
      port: 12201

management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always
management.health.elasticsearch.enabled: false



spring: ## General Config
   main:
      allow-circular-references: true
      allow-bean-definition-overriding: true
   application.name: onesaitplatform-spark-launcher-manager
   boot.admin: #Spring Boot Admin Config
      client.url: http://localhost:18100/monitoring
      client.username: operations
      client.password: changeIt2019!
      client.instance.metadata.user.name: ${spring.boot.admin.client.username}
      client.instance.metadata.user.password: ${spring.boot.admin.client.password}

   datasource:
     hikari:
      jdbc-url: jdbc:mysql://localhost:3306/onesaitplatform_config?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true&nullDatabaseMeansCurrent=true
      username: root
      password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph)
      connection-timeout: 10000
      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:postgresql://localhost:5432/onesaitplatform_config
#      username: postgres
#      password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph)
#      driver-class-name: org.postgresql.Driver
      minimum-idle: 10
      maximum-pool-size: 30

   jpa:
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#      properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
      # Hibernate ddl auto (create, create-drop, validate, update
      hibernate.ddl-auto: validate
      properties:
        hibernate:
          format_sql: false
          show_sql: false

   jmx:
    enabled: true
spring.elasticsearch.jest.uris: ${onesaitplatform.database.elasticsearch.sql.connector.http.endpoint}
spring.elasticsearch.jest.read-timeout: ${onesaitplatform.database.elasticsearch.sql.connectionTimeout.millis}

## LOGGING CONF
logging:
   file.path: ./target/
   file.name: ${spring.application.name}
   level:
      com.minsait: INFO
      org.springframework.boot: INFO
      org.apache.kafka: ERROR
#      org.springframework.boot.autoconfigure: DEBUG
