sofia2: #Config Sofia2 specific
   database.mongodb:
      servers: realtimedb:27017
      quasar.connector.http.endpoint: http://quasar:10800/query/fs/ 
   
spring: ## General Config  
   datasource: ## JPA Config
      url: jdbc:mysql://configdb:3306/onesaitplatform_config?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false