server: ## Config Web Server
   port: 19200
   contextPath: /devicesimulator


# all access to actuator endpoints without security
management.security.enabled: false
master: 
   datasource:
      url: jdbc:mysql://localhost:3306/onesaitplatform_master_config?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true
      username: root
      password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
      driver-class-name: com.mysql.jdbc.Driver
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1      
      validationQueryTimeout: 5
      # Number of ms to wait before throwing an exception if no connection is available.
      max-wait: 10000
      # Maximum number of active connections that can be allocated from this pool at the same time.
      max-active: 2
      initial-size: 1
      max-idle: 2
      min-idle: 1
      removeAbandoned: true
spring:
   application.name: onesaitplatform-device-simulator
   boot.admin: #Spring Boot Admin Config   
      url: http://localhost:18100/monitoring
      username: operations
      password: ENC(2Xd2AOD2NrMaWs915/st8C4ILo3qlHXv)
      client.metadata.user.name: ${spring.boot.admin.username}
      client.metadata.user.password: ${spring.boot.admin.password}
   data.mongodb:
      database: onesaitplatform_rtdb # Database name.
  
   ## JPA Config
   datasource:
      url: jdbc:mysql://localhost:3306/onesaitplatform_config?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true&nullDatabaseMeansCurrent=true
      username: root
      password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
      driver-class-name: com.mysql.jdbc.Driver
      # Validate the connection before borrowing it from the pool.
      test-on-borrow: true
      validation-query: SELECT 1
      validationQueryTimeout: 5
      test-while-idle: true       
      # Number of ms to wait before throwing an exception if no connection is available.
      max-wait: 10000
      # Maximum number of active connections that can be allocated from this pool at the same time.
      max-active: 30
      initial-size: 10
      max-idle: 30
      min-idle: 10
      removeAbandoned: true
      
   jpa:
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
quartz:      
   datasource:
      # This property has to be configured in a profile in the pom.xml. Currently, it is configured in the parent project.
      url: "@onesaitplatform.quartzURL@"
      username: root
      password: ENC(v6o0Jud8aASYCkRb+u0RTICFUR8Pd5ph) 
      driver-class-name: com.mysql.jdbc.Driver
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1
      # Number of ms to wait before throwing an exception if no connection is available.
      max-wait: 10000
      # Maximum number of active connections that can be allocated from this pool at the same time.
      max-active: 10
      initial-size: 3
      max-idle: 10
      min-idle: 3
   jpa:
      ## Hibernate Properties
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      # Hibernate ddl auto (create, create-drop, validate, update)
      properties.hibernate.hbm2ddl.auto: update
      properties.hibernate.hbm2ddl.import_files: /quartz-schema.sql
   autoStartupSchedulers:
      - simulationScheduler
    
onesaitplatform: #Config Sofia2 specific
   audit.global.notify: true
   iotbroker:
      server: http://localhost:19000/iotbroker
   database.elasticsearch:
      database: onesaitplatform_rtdb_es
      sql.maxHttpConnections: 10
      sql.maxHttpConnectionsPerRoute: 10
      sql.connectionTimeout.millis: 10000
      sql.connector.http.endpoint: http://localhost:9200
      url: localhost
      port: 9300
            
## LOGGING CONF
logging:
   path: ./target/ 
   file: ${spring.application.name}
   level:
      com.minsait: INFO 
