master:
   datasource:
     hikari:
      jdbc-url: ${CONFIGDBMASTERURL}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}
      driver-class-name: ${CONFIGDB_DRIVER}

onesaitplatform:
   iotbroker:
      server: http://iotbrokerservice:19000/iotbroker
   router.alternativeURL: http://routerservice:20000/router/router/
   audit.global.notify: ${AUDITGLOBALNOTIFY}
   graylog:
      enabled: ${GRAYLOG_ENABLED}
      host: ${GRAYLOG_HOST}
      port: ${GRAYLOG_PORT}
spring:
   datasource:
     hikari:
      jdbc-url: ${CONFIGDBURL}
      username: ${CONFIGDBUSER}
      password: ${CONFIGDBPASS}
      connection-timeout: ${DS_MAX_WAIT_MILLIS}
      maximum-pool-size: ${DS_MAX_ACTIVE}
      minimum-idle: ${DS_MIN_IDLE}
      driver-class-name: ${CONFIGDB_DRIVER}
   boot.admin: #Spring Boot Admin Config
      client.url: http://monitoringuiservice:18100/monitoring
      client.instance.service-url: http://devicesimulator:${server.port}${server.servlet.contextPath}/
      client.username: ${SBA_USERNAME}
      client.password: ${SBA_SECRET}
   jpa:
      properties.hibernate.dialect: ${CONFIGDB_DIALECT}
quartz:
    datasource:
      hikari:
        jdbc-url: ${SCHEDULERDBBURL}${DBADDPROPS}
        username: ${SCHEDULERDBBUSER}
        password: ${SCHEDULERDBBPASS}
        driver-class-name: ${SCHEDULERDBBDRIVER}
    jpa:
      properties.hibernate.dialect: ${SCHEDULERDBBDIALECT}
    driverDelegateClass: ${QUARTZ_DRIVER}
## LOGGING CONF
logging:
   file.path: /var/log/platform-logs
